### ISSUE TITLE
Compatibility with Composer 2 / Magento 2.4.2

### ISSUE THREAD

**Issue by norgeindian** [fooman/composer-magento2-optimizations#4]
Since version 2.4.2, Magento supports Composer 2.
But using Composer 2 fails, as this module requires `composer-plugin-api ^1.1`.
It would be great to have a compatible version to still use this great improvement.

**Comment by sprankhub** [comment]
`zaporylie/composer-drupal-optimizations`, on which this repo is based, decided to basically not do anything when Composer 2 is detected, because it should be fast enough by default: https://github.com/zaporylie/composer-drupal-optimizations/pull/17/

I suggest doing two things here:

1. Implement the same "do nothing for Composer 2" code.
2. Evaluate if this plugin is still valuable for Composer 2.

**Comment by fooman** [comment]
Add a notice to suggest removal of the plugin
![image](https://user-images.githubusercontent.com/455508/110863202-34ee6780-8325-11eb-90e6-f7dd70063f92.png)

Composer 2.0 out of the box is already solving quite a bit of what this plugin provided. Composer 2.1 should solve this particular fix globally.
